doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                logging: false

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            JobSearcher:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'JobSearcher\Entity'
                alias: JobSearcher
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool

        dql:
            string_functions:
                MD5: DoctrineExtensions\Query\Mysql\Md5
                CAST: DoctrineExtensions\Query\Mysql\Cast
                IF: DoctrineExtensions\Query\Mysql\IfElse
            datetime_functions:
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                NOW: DoctrineExtensions\Query\Mysql\Now

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
