configuration:
  name: "kimeta.de"
  enabled: true

crawler_configuration:

  scrap_pagination:
    engine: !php/const WebScrapperBundle\Service\CrawlerService::CRAWLER_ENGINE_GOUTTE
    wait_for_dom_element_selector_name: ""
    wait_for_function_to_return_true: ""
    wait_milliseconds: null

  scrap_job_offer_detail:
    engine: !php/const WebScrapperBundle\Service\CrawlerService::CRAWLER_ENGINE_GOUTTE
    wait_for_dom_element_selector_name: ""
    wait_for_function_to_return_true: ""
    wait_milliseconds: null

host: "https://www.kimeta.de"

search_uri:
  base_host: null
  base_uri:
    standard: "/search?q="
  keywords_placement: !php/const JobSearcher\Service\JobService\ConfigurationBuilder\ConfigurationBuilderInterface::KEYWORDS_PLACEMENT_QUERY
  encode_query: true

  location:
    placement: !php/const JobSearcher\Service\JobService\ConfigurationBuilder\Constants\LocationSearchUriConstants::LOCATION_PLACEMENT_QUERY
    spacebar_replace_character: "+"
    query:
      param_name: "loc"
    distance:
      placement: !php/const JobSearcher\Service\JobService\ConfigurationBuilder\Constants\LocationSearchUriConstants::LOCATION_PLACEMENT_QUERY
      query:
        param_name: "r"
      allowed_distances: {
        0: 0,
        10: 10,
        20: 20,
        30: 30,
        40: 40,
        50: 50,
        100: 100
      }

# bug: the pagination parameter seems to be wrong
pagination:
  start_value: 0
  increment_value: 1
  multiple_keywords_separator_character: "+"
  pagination_spacebar_in_keyword_words_replace_character: "+"
  page_number_query_parameter_name: "r"

links:
  detail_page:
    replace_regex_rules:
      '#&coe=searchGroupId(.*)#': ""
      '#&searchId=(.*)\&#U': "&"

selectors:

  #bug - pagination selectors seems to be wrong, see: jobs.de / de.indeed - this is probably working just by LUCK
  # this special selector will fetch job offers card/blocks on pagination, is also used as fallback to get offer uri in case when the block itself is a link
  pagination_page_offer_block:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_PAGINATION_PAGE_OFFER_BLOCK
    css_selector: "a[href^='/search?q'][rel='nofollow'].jli"
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  pagination_page_job_title:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_PAGINATION_PAGE_JOB_TITLE
    css_selector: "h3"
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  pagination_page_company_name:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_PAGINATION_PAGE_COMPANY_NAME
    css_selector: "span"
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  pagination_page_link_to_detail_page:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_PAGINATION_PAGE_LINK_TO_DETAIL_PAGE
    css_selector: "a[href^='/search?q'][rel='nofollow'].jli"
    target_attribute_name: "href"
    get_data_from_inner_text: false
    get_data_from_attribute: true
    called_method: null

  job_name_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_OFFER_DETAIL_JOB_NAME
    css_selector: ".job-header h2"
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  job_description_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_OFFER_DETAIL_JOB_DESCRIPTION
    css_selector: "#jobtempl .content, .content-innerhtml"
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  job_offer_job_posted_date_time:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_OFFER_DETAIL_JOB_POSTED_DATE_TIME
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  company_location_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_COMPANY_WORKPLACE_DATA_LOCATION
    css_selector: ".location-offer h4"
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  company_name_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_COMPANY_WORKPLACE_DATA_COMPANY_NAME
    css_selector: ".job-header h3"
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  contact_company_email:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_CONTACT_DETAIL_COMPANY_EMAIL
    css_selector: "#jobtempl .content, .content-innerhtml"
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: !php/const JobSearcher\Service\JobSearch\Scrapper\BaseScrapperService::METHOD_EXTRACT_EMAIL_FROM_STRING

  contact_company_phone:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_CONTACT_DETAIL_COMPANY_PHONE
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  salary_min_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_SALARY_MIN
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  salary_max_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_SALARY_MAX
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  salary_estimated_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_SALARY_ESTIMATED
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  remote_work_possible_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_REMOTE_WORK_POSSIBLE
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null
