monolog:
    handlers:
        main:
            type: rotating_file
            action_level: error
            handler: nested
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            max_files: 14
            path: "%kernel.logs_dir%/%kernel.environment%.log"
        nested:
            type: stream
            path: php://stderr
            level: warning
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console", "!shell"]