configuration:
  name: "infopraca.pl"
  enabled: true

crawler_configuration:

  scrap_pagination:
    engine: !php/const WebScrapperBundle\Service\CrawlerService::CRAWLER_ENGINE_CLI_CURL
    wait_for_dom_element_selector_name: ""
    wait_for_function_to_return_true: ''
    wait_milliseconds: null
    headers:
      content-type: text/html
      accept: text/html

  scrap_job_offer_detail:
    engine: !php/const WebScrapperBundle\Service\CrawlerService::CRAWLER_ENGINE_GOUTTE
    wait_for_dom_element_selector_name: ''
    wait_for_function_to_return_true: ''
    wait_milliseconds: null

host: "https://www.infopraca.pl"

search_uri:
  base_host: null

  base_uri:
    standard: "/praca?q="
    sorted_latest_first: "/praca?sort=last_update&q="

  keywords_placement: !php/const JobSearcher\Service\JobService\ConfigurationBuilder\ConfigurationBuilderInterface::KEYWORDS_PLACEMENT_QUERY

  location:
    placement: !php/const JobSearcher\Service\JobService\ConfigurationBuilder\Constants\LocationSearchUriConstants::LOCATION_PLACEMENT_QUERY
    query:
      param_name: "lc"
    distance:
      placement: !php/const JobSearcher\Service\JobService\ConfigurationBuilder\Constants\LocationSearchUriConstants::LOCATION_PLACEMENT_QUERY
      query:
        param_name: "d"
      allowed_distances: {
        0: 0,
        5: 5,
        10: 10,
        15: 15,
        20: 20,
        25: 25,
        35: 35,
        50: 50
      }

  encode_query: true

pagination:
  start_value: 1
  increment_value: 1
  multiple_keywords_separator_character: "+"
  pagination_spacebar_in_keyword_words_replace_character: "+"
  page_number_query_parameter_name: "pg" # fake param name for building links, no way to disable pagination

selectors:

  # this special selector will fetch job offers card/blocks on pagination, is also used as fallback to get offer uri in case when the block itself is a link
  pagination_page_offer_block:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_PAGINATION_PAGE_OFFER_BLOCK
    css_selector: '.job-offer'
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  pagination_page_job_title:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_PAGINATION_PAGE_JOB_TITLE
    css_selector: 'a:not([data-bs-toggle])'
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  pagination_page_company_name:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_PAGINATION_PAGE_COMPANY_NAME
    css_selector: 'h2'
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  pagination_page_link_to_detail_page:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_PAGINATION_PAGE_LINK_TO_DETAIL_PAGE
    css_selector: 'h1.h3 a'
    target_attribute_name: "href"
    get_data_from_inner_text: false
    get_data_from_attribute: true
    called_method: null

  # Detail page
  job_name_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_OFFER_DETAIL_JOB_NAME
    css_selector: '.box__title h1, .job-external-template__title h1'
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  job_description_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_OFFER_DETAIL_JOB_DESCRIPTION
    css_selector: '.box__content, .job-external-template #template'
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  company_location_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_COMPANY_WORKPLACE_DATA_LOCATION
    css_selector: '.job-external-template .icon-geo-alt + a, .icon-geo-alt+*'
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  company_name_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_COMPANY_WORKPLACE_DATA_COMPANY_NAME
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

# Not present
  contact_company_email:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_CONTACT_DETAIL_COMPANY_EMAIL
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: !php/const JobSearcher\Service\JobSearch\Scrapper\DomHtml\ScrapperInterface::METHOD_EXTRACT_EMAIL_FROM_STRING

  contact_company_phone:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_CONTACT_DETAIL_COMPANY_PHONE
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  salary_min_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_SALARY_MIN
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  salary_max_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_SALARY_MAX
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  salary_estimated_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_SALARY_ESTIMATED
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: null

  remote_work_possible_selector:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_REMOTE_WORK_POSSIBLE
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: !php/const JobSearcher\Service\JobSearch\Scrapper\DomHtml\ScrapperInterface::METHOD_IS_REMOTE_WORK_POSSIBLE

  job_offer_job_posted_date_time:
    dom_element_purpose: !php/const JobSearcher\DTO\JobSearch\DOM\DomElementConfigurationDto::PURPOSE_DETAIL_PAGE_OFFER_DETAIL_JOB_POSTED_DATE_TIME
    css_selector: null
    target_attribute_name: null
    get_data_from_inner_text: true
    get_data_from_attribute: false
    called_method: !php/const JobSearcher\Service\JobSearch\Scrapper\DomHtml\ScrapperInterface::METHOD_IS_REMOTE_WORK_POSSIBLE
