# Info: has salary data under `salaire` so could extend this in future
configuration:
  name: "1jeune1solution.gouv.fr"
  enabled: true

host: "https://www.1jeune1solution.gouv.fr"

search_uri:
  base_host: "http://www.1jeune1solution.gouv.fr" # https MUST be skipped here
  base_uri:
    standard: "/_next/data/"

  resolver: 'JobSearcher\Service\JobService\Resolver\API\Fr\JeuneSolutionGouvFrResolver->buildSearchUri'
  keywords_placement: !php/const JobSearcher\Service\JobService\ConfigurationBuilder\ConfigurationBuilderInterface::KEYWORDS_PLACEMENT_QUERY

  method: !php/const Symfony\Component\HttpFoundation\Request::METHOD_GET
  request:
    headers:
      host:
        name: "host"
        value: 'www.1jeune1solution.gouv.fr'
      accept:
        name: "accept"
        value: '*/*'
      user_agent:
        name: "user-agent"
        value: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

pagination:
  start_value: 1
  increment_value: 1
  multiple_keywords_separator_character: "+"
  pagination_spacebar_in_keyword_words_replace_character: "+"
  page_number_query_parameter_name: "page"

detail_page:
  method: null

json_structure:
  all_jobs: "pageProps.resultats.résultats"
  job_detail:
    url: "urlOffreOrigine"
    title: "intitulé"
    location:
      type: !php/const JobSearcher\DTO\JobService\SearchConfiguration\Api\JsonStructureConfigurationDto::LOCATION_TYPE_SINGLE_PATH
      single_entry_path: "lieuTravail"
      array_structure_path: null
    description: 'description'
    company_name: 'entreprise.nom'
    more_information: null
    job_posted_date_time: null
    detail_page_identifier_field: ''
